myproject/musicfile/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'musicfile'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='contentofindex'),
    url(r'^register/$', views.LoginView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='DetailOfAlbums'),

    url(r'^album/add/$', views.AlbumCreate.as_view(), name='AlbumCreate'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='AlbumUpdate'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='AlbumDelete'),


    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from webapp import views
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls import url, include
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),

    url(r'^admin/', admin.site.urls, name='about'),

    url(r'^employees/', views.employeesList.as_view()),
    url(r'^music/', include('musicfile.urls'), name='about-music'),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url('', include('blog.urls')),
    url('', include('errorapp.urls')),
    url('api/', include('posts.urls')),
    url('', include('data.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.sites.AdminSite.site_header = 'Administration'
admin.sites.AdminSite.site_title = 'Administration'
admin.sites.AdminSite.index_title = 'Administration'

handler404 = 'errorapp.views.error_404_view'

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from webapp import views

from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls import url, include
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    # path('about/', views.AboutPageView.as_view(), name='about'),
    url(r'^admin/', admin.site.urls, name='about'),
    url(r'^employees/', views.employeesList.as_view()),
    url(r'^music/', include('musicfile.urls'), name='about-music'),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url('', include('blog.urls')),


]

myproject/musicfile/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    region = models.CharField(max_length=250)
    logo = models.ImageField(upload_to='album_pic',blank=True)

    # to show correct in list view without showing object name in admin page
    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse('musicfile:DetailOfAlbums', kwargs={'pk': self.pk})



class Songs(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=250)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

myproject/musicfile/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Songs





class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

myproject/musicfile/views.py
from django.shortcuts import render,get_object_or_404
from .models import Album,Songs
from .forms import UserForm
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy,reverse
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout


#
# def index(request):
#     all_albums = Album.objects.all()
#     return render(request, 'music/index.html',{'all_albums': all_albums},)
#
# def detail(request, album_id):
#     # import pdb; pdb.set_trace()
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request,'music/detail.html', {'album': album})

def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        # import pdb; pdb.set_trace()
        selected_song = album.songs_set.get(pk=request.POST['song'])
    except (KeyError, Songs.DoesNotExist):
        raise
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "No song selected"
        })

    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})



class IndexView(ListView):
    template_name = "music/index.html"
    context_object_name ='all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(DetailView):
    template_name = "music/detail.html"
    model = Album


class AlbumCreate(CreateView):
    template_name = "music/album_form.html"
    model = Album
    fields = ['artist','album_title','region','logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','region','logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy("musicfile:contentofindex")




class LoginView(DetailView):
    form_class = UserForm
    template_name = "music/registration.html"

    # display empty form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()


            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect(reverse('musicfile:contentofindex'))
        return render(request,self.template_name,{'form':form})

myproject/musicfile/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    <!-- {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %} -->
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Viberr?</h3>
                    <p>Viberr is an app that allows you to upload and store all of your music on the cloud.</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div> -->

    </div>

</div>
{% endblock %}

myproject/musicfile/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <em><a class="navbar-brand" href="{% url 'musicfile:contentofindex' %}">Palani</a></em>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'musicfile:contentofindex' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a>
                </li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'musicfile:contentofindex'  %}">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'musicfile:contentofindex' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'musicfile:AlbumCreate' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'musicfile:contentofindex' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

myproject/musicfile/templates/music/detail.html
{% extends 'music/base.html' %}
<title>{% block title %}Album Details{% endblock %}</title>
{% load staticfiles %}

{% block body %}

<img src="{{album.logo.url}}" alt="album_art" style="width:200px">
<h2>{{ album.album_title }}</h2>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'musicfile:favourite' album.id  %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    {% for song in album.songs_set.all %}
        <label for="song {{ forloop.counter }}"><input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        {{song.song_title}}
        {% if song.is_favourite %}
        <img src="https://cdn4.iconfinder.com/data/icons/Sizicons/16x16/star_blue.png" alt="fav_star">
            {% endif %}
        </label> </br>

    {% endfor %}
<br>
        <input type="submit" value="Favourite"></input>
</form>

{% endblock %}

myproject/musicfile/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

myproject/musicfile/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'musicfile/style.css' %}">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<div class="col-sm-12">
    <h3>{{ user.username }}'s Albums</h3>
</div>

{% if all_albums %}

  {%for album in all_albums%}
  <div class="col-sm-4 col-lg-2">
    <div class="thumbnail">
      <a href="{% url 'musicfile:DetailOfAlbums' album.id %}">
        <img src="{{ album.logo.url }}" class="img-responsive">
      </a>
      <div class="caption">
                           <h2>{{ album.album_title }}</h2>
                           <h4>{{ album.artist }}</h4>



<a href="{% url 'musicfile:DetailOfAlbums' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

<!-- Delete Album -->
            <form action="{% url 'musicfile:AlbumDelete' album.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>

                          <!-- Favorite Album -->
              <!-- <a href="{% url 'musicfile:favourite' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                  <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
              </a> -->

            </div>
        </div>
    </div>

  {%endfor%}

{% else %}

<h1> you don't have any albums please create  </h1>

{%endif%}
{% endblock %}

myproject/musicfile/templates/music/registration.html
{% extends 'music/base.html' %}
{% block title %}register{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Acoount</h3>

                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}