myproject/musicfile/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'musicfile'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='contentofindex'),
    url(r'^register/$', views.LoginView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='DetailOfAlbums'),

    url(r'^album/add/$', views.AlbumCreate.as_view(), name='AlbumCreate'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='AlbumUpdate'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='AlbumDelete'),


    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myproject/myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from webapp import views
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls import url, include
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),

    url(r'^admin/', admin.site.urls, name='about'),

    url(r'^employees/', views.employeesList.as_view()),
    url(r'^music/', include('musicfile.urls'), name='about-music'),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url('', include('blog.urls')),
    url('', include('errorapp.urls')),
    url('api/', include('posts.urls')),
    url('', include('data.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.sites.AdminSite.site_header = 'Administration'
admin.sites.AdminSite.site_title = 'Administration'
admin.sites.AdminSite.index_title = 'Administration'

handler404 = 'errorapp.views.error_404_view'

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from webapp import views

from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls import url, include
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    # path('about/', views.AboutPageView.as_view(), name='about'),
    url(r'^admin/', admin.site.urls, name='about'),
    url(r'^employees/', views.employeesList.as_view()),
    url(r'^music/', include('musicfile.urls'), name='about-music'),

    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url('', include('blog.urls')),


]

myproject/webapp/urls.py
from django.urls import include,path
from . import views
from django.views.generic.base import TemplateView # new

# app_name = 'webapp'
urlpatterns = [
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^blogs/', include('blog.urls', namespace='blog')),
    # url(r'^employees/', views.employeesList.as_view()),



]

myproject/webapp/models.py
from django.db import models

# Create your models here.

class employees(models.Model):
	firstname = models.CharField(max_length=10)
	lastname = models.CharField(max_length=10)
	emp_id = models.IntegerField()

	def __str__(self):
		return self.firstname

myproject/webapp/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.db import connection, models, transaction
from django.http import Http404
from django.http.response import HttpResponseBase
from django.utils.cache import cc_delim_re, patch_vary_headers
from django.utils.encoding import smart_text
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView
from rest_framework import exceptions, status
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.schemas import DefaultSchema
from rest_framework.settings import api_settings
from rest_framework.utils import formatting
from . models import employees
from . serializers import employeesserializers
from django.views.generic import TemplateView

#
def login(request):
    return render(request, 'blog/templates/registration/login.html')


class HomePageView(TemplateView):
    template_name = 'home.html'

class AboutPageView(TemplateView):
    template_name = 'about.html'

class employeesList(APIView):

    def get(self,request):
        employees1 = employees.objects.all()
        serializer = employeesserializers(employees1, many=True)
        return Response(serializer.data)

    #
    # def post(self, request):
    #     employees1 = employees.objects.all()
    #     serializer = employeesserializers(employees1, many=True)
    #     if serializer.is_valid(raise_exception=True):
    #         employees_saved = serializer.save()
    #     return Response({"success": "employees '{}' updated successfully".format(employees_saved.temp_id)})
    #
    #
    # def put(self, request, pk):
    #     employees_saved = get_object_or_404(employees.objects.all(), pk=pk)
    #     data = request.data.get('employees')
    #     serializer = employeesserializers(instance=employees_saved, data=data, partial=True)
    #     if serializer.is_valid(raise_exception=True):
    #         employees_saved = serializer.save()
    #     return Response({"success": "employees '{}' updated successfully".format(employees_saved.temp_id)})
    #
    #
    # def delete(self, request, pk):
    #
    #     article = get_object_or_404(employees.objects.all(), pk=pk)
    #     article.delete()
    #     return Response({"message": "employees with id `{}` has been deleted.".format(pk)},status=204)
    

from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from . serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

myproject/webapp/templates/base.html
<!-- {% block content %}
{% endblock %} -->

myproject/webapp/templates/home.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/portopolio.css' %}">
    <script src="{% static 'js/portopolio.js' %}"></script>

</head>

<body>
  <div class="topnav">
    <a  href="{% url 'home' %}">Home</a>
    {% if user.is_authenticated %}

    <div class="dropdown">
    <button class="dropbtn">Blogs
        <i class="fa fa-caret-down"></i>
      </button>

      <div class="dropdown-content">
    <a  href="{% url 'post_new' %}">Create Blog</a>
    <a  href="{% url 'post_list' %}">Blog List</a>
    <a  href="{% url 'post_draft_list' %}">Draft Blogs</a>




  </div>
  </div>
  <div class="dropdown">
  <button class="dropbtn">Media
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
  <a  href="{% url 'musicfile:contentofindex' %}">Media Index</a>
  </div>
  </div>

  {% endif %}

    <div class="topnav-right">
      <div class="dropdown">
      <button class="dropbtn">About
          <i class="fa fa-caret-down"></i>
        </button>
      <div class="dropdown-content">
      <a href ="#about-me">About</a>
      <a href ="#portfolio">Portfolio</a>
      <a href ="#contact">Contact</a>
        </div>
      </div>

      {% if user.is_authenticated %}

      <div class="dropdown">
      <button class="dropbtn">Profile
          <i class="fa fa-caret-down"></i>
        </button>
      <div class="dropdown-content">

          <a  href="{% url 'profile' %}">View profile</a>
          <a  href="{% url 'profile_edit' %}">Edit profile</a>
          <a  href="{% url 'change_password' %}">Change password</a>
          <a  href="{% url 'password_reset' %}">Password reset</a>
      </div>
    </div>

      <a  href="{% url 'logout' %}">logout</a>
      {% else %}
      <a  href="{% url 'register' %}">Register<n/a>
      <a  href="{% url 'login' %}">Login<n/a>

      {% endif %}
    </div>
  </div>

</body>



<div class ="container-fluid" id ="section1">

  <div class ="row">
    <div class ="banner" id="home">
      <br><br><br><br><br><br><br><br>
      <h2>HELLO I'M</h2><br>


    <h2>PALANISAMY P</h2><br>
    <h3>Python/Django Developer</h3><br>

      <h5>Pleasure in the job puts perfection in the work</h5><br>
        <div class ="row">
    <div class ="button-group">
      <a href="https://www.facebook.com/palanigct1994" target ="blank"><button class ="btn  btn-primary ba">Facebook<i class ="fa fa-facebook"></i></button></a>
     <a href="https://github.com/palani4194/" target ="blank"> <button class ="btn  btn-primary ba">Github<i class ="fa fa-github"></i></button></a>
      <a href="https://www.linkedin.com/in/palani-p-9623a511a/" target ="blank"><button class ="btn  btn-primary ba">LinkedIn<i class ="fa fa-linkedin" aria-hidden="true;"></i></button></a>
     <a href ="https://bitbucket.org/palani4194/" target ="blank"> <button class ="btn  btn-primary ba">Bitbucket<i class ="fa fa-free-code-camp fa-fw "></i></button></a>
    <br/>
    <br/>
    <br/>
    <br/>


     <a href="{% static 'css/PALANI_BE_CV.docx'%}" style="color: white; font-size: 30px;" target="_new">Download Resume</a>
     <br/>
     <br/>
     <br/>
     <a href="mailto:palanigct1994@gmail.com" style="color: white; font-size: 30px;">palanigct1994@gmail.com</a>
     <br/>
     <br/>
     <br/>
     <a href="9894822885" style="color: white; font-size: 30px;">9894822885</a>
     <br/>
     <br/>




     <br><br><br>

    </div>
    </div>
    </div>
</div>

  <div class ="row">
  <div class ="about-me " id="about-me">
    <div class ="overlay">
      <div class ="row">

      <p>I m a 25 year old Engineering student from GCT-Coimbatore,India. I studied Computer Science Engineering and I have a passion for Web development. I am  self taught and I use my free time to develop pages. My Passion is to use my skills and technologies to help solve real world challenges.
<br/>
<br/>

 Languages     : Python 3.5, XML, Postgresql 9.3, HTML 5, CSS 3, Core java, JavaScript. <br/><br/>
 Frameworks  : Odoo 11, Django 2.0, DRF(Django Rest Framework).<br/><br/>
 Course           : Completed Core Java  Course in NIIT Chennai.<br/><br/>
 Other Skills   : IDE - Pycharm, Eclipse & Atom, Version Control - GitHub, Web server - NGINX , AWS.<br/><br/>
 Environment : ERP and CRM App Development, Enhancement - Ubuntu 16.04 / Linux Environment.<br/><br/>




            <br/>

            </p>
      </div>
    </div>
  </div>
</div>

<!--projects -->
<div class ="row">
  <div class ="portfolio" id="portfolio">
    <div class ="overlay2">

        <div class="container">
                <div class="col-lg-12 text-center">
                  <center>  <h2>Portfolio</h2></center>
                  <br/>
                  <br/>
                  <br/>

                </div>
  <a href="https://www.cbazaar.com" target="_blank"> <img  src="{% static 'images/cbazaar.jpeg' %}" alt="cbazaar"  width="200" height="200"></a>
  <a href="https://www.petrogistix1.com" target="_blank"> <img  src="{% static 'images/petrogistix.png' %}" alt="petrogistix" ></a>
  <a href="http://goldengrains.biz" target="_blank"> <img  src="{% static 'images/Golden-Grain-Logo-1.png' %}" alt="Golden-Grain" width="330" height="230"></a>
  <a href="http://www.medmanpharmacy.com/" target="_blank"> <img  src="{% static 'images/medicine_man.png' %}" alt="Girl in a jacket" width="200" height="200"></a>
  <a href="http://balbina.ae/" target="_blank"> <img  src="{% static 'images/balbina.jpg' %}" alt="balbina" width="200" height="200"></a>
  <a href="https://www.180smoke.com/" target="_blank"> <img  src="{% static 'images/180_smoke.jpeg' %}" alt="180_smoke" width="200" height="200"></a>
  <a href="https://www.ge.com/" target="_blank"> <img  src="{% static 'images/ge.png' %}" alt="ge" width="200" height="200"></a>




<br> </br>
<br> </br>
<br> </br>
<br> </br>
<br> </br>

<center>
  <h3 id="below-section" class="section-subheading">Please find my some of my works above.</h3>
  <br> </br>

  <h3 id="below-section" class="section-subheading">These projects I was working in a ERP & CRM Application and E-Commerce websites too.</h3>
  <br> </br>

  <h3 id="below-section" class="section-subheading">I am a Python/Django Developer for Web Applications like ERP & CRM.</h3>

  </center>

                </div>

            </div>
        </div>

    </div>


  <div class ="row">
  <div class ="contact" id="contact">
       <div class="contact-header">
         <br></br>
            <h1>I'd like to hear from you.
              <br></br>
              <br></br>

            </h1>
            <h2> Name: PALANISAMY P</h2>
            <h2> Phone: 9894822885 </h2>
            <h2>  Email: palanigct1994@gmail.com </h2>
            <h2>  Skype: palani4194 </h2>

          </div>
    <div class ="row">
     <div class="col-md-6 contact-text">
              <!-- <h3>Want to get in touch with me? Feel free to reach out to me at any time.
              </h3> -->
            </div>

    </div>
  </div>
</div>
    </div>
    <footer id="colophon" class="site-footer" role="contentinfo">
      <div class="social-wrapper">
        <ul>

          <li>
            <a href="https://www.linkedin.com/in/palani-p-9623a511a/" target="_blank">
              <img src="http://icons.iconarchive.com/icons/limav/flat-gradient-social/48/Linkedin-icon.png" alt="Linkedin Logo" class="linkedin-icon"></a>
          </li>
          <li>
            <a href="https://www.facebook.com/palanigct1994" target="_blank">
              <img src="http://www.iconarchive.com/download/i54037/danleech/simple/facebook.ico" alt="Facebook Logo" class="facebook-icon"></a>
          </li>
          <li>
            <a href="https://plus.google.com/" target="_blank">
              <img src="http://icons.iconarchive.com/icons/marcus-roberto/google-play/256/Google-plus-icon.png" alt="Googleplus Logo" class="googleplus-icon"></a>
          </li>


        </ul>
      </div>

      <nav class="footer-nav" role="navigation">
        <p>Copyright &copy; Palani Web Design 2018. All Rights Reserved</p>
      </nav>
    </footer>